version: '3.8'

services:
  mqtt:
    image: eclipse-mosquitto:latest
    container_name: mqtt
    ports:
      - "1883:1883"
    networks:
      - mqtt-net
    volumes:
      - /home/rares/Documents/scd/tema3/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mqtt-volume:/mosquitto
  iot_payload:
    image: iot_payload
    container_name: iot_payload
    networks:
      - mqtt-net
  iot_reciever:
    image: iot_reciever
    container_name: iot_reciever
    networks:
      - mqtt-net

networks:
  mqtt-net:

volumes:
  mqtt-volume: