version: '3.8'

services:
  mqtt:
    image: eclipse-mosquitto:latest
    container_name: mqtt
    ports:
      - "1883:1883"
    networks:
      - mqtt-net-payload
      - mqtt-net-receiver
    restart: always
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  iot_payload:
    image: iot_payload
    container_name: iot_payload
    depends_on:
      - mqtt
    networks:
      - mqtt-net-payload
    restart: always
  
  iot_receiver:
    image: iot_receiver
    depends_on:
      - mqtt
      - influx
    container_name: iot_receiver
    networks:
      - mqtt-net-receiver
      - influx-net
    restart: always
    environment:
      - DEBUG_DATA_FLOW=false
  
  influx:
    image: influxdb:1.8
    container_name: influx
    environment:
      - INFLUXDB_DB=scd
    ports:
      - "8086:8086"
    networks:
      - influx-net
      - grafana-net
    volumes:
      - influx-volume:/var/lib/influxdb
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - influx
    ports:
      - "80:3000"
    networks:
      - grafana-net
    volumes:
      - grafana-volume:/var/lib/grafana
    environment:
      - "GF_SECURITY_ADMIN_USER=asistent"
      - "GF_SECURITY_ADMIN_PASSWORD=grafanaSPRC2024"
    restart: always

networks:
  mqtt-net-receiver:
  mqtt-net-payload:
  influx-net:
  grafana-net:

volumes:
  influx-volume:
  grafana-volume: