version: '3.8'

services:
  mqtt:
    image: eclipse-mosquitto:latest
    container_name: mqtt
    ports:
      - "1883:1883"
    networks:
      - mqtt-net-payload
      - mqtt-net-receiver
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mqtt-volume:/mosquitto

  iot_payload:
    image: iot_payload
    container_name: iot_payload
    networks:
      - mqtt-net-payload
  
  iot_receiver:
    image: iot_receiver
    container_name: iot_receiver
    networks:
      - mqtt-net-receiver
      - influx-net
  
  influx:
    image: influxdb:1.8
    container_name: influx
    environment:
      - INFLUXDB_DB=scd
    ports:
      - "8086:8086"
    networks:
      - influx-net
    volumes:
      - influx-volume:/var/lib/influxdb
    restart: always
    # deploy:
    #   placement:
    #     constraints: [node.role == manager]

networks:
  mqtt-net-receiver:
  mqtt-net-payload:
  influx-net:

volumes:
  mqtt-volume:
  influx-volume: